implemented authorization
PawelS1988/nodejs-homework-rest-api pull request #3
Opened 2022-04-11 13:27 UTC by PawelS1988

please take a look

2022-04-12 11:22 UTC, mkubera requested changes
OK. Jest troche zmian do zrobienia, ale nic duzego :)

2022-04-12 11:22 UTC, mkubera commented on routes/api/contacts.js
> +} = require("./utils");
`utils.js` nie istnieje o_o

2022-04-12 11:22 UTC, mkubera commented on routes/api/contacts.js
> +  const contact = await getContactById(req.params.contactId, owner);
zrob raczej, jako `const { contactId } = req.params.contactId;` i potem `getContactById(contactId, owner);`
Bedzie bardziej czytelnie :)

2022-04-12 11:22 UTC, mkubera commented on routes/api/contacts.js
> +  const { _id: owner } = req.user;
tutaj pewnie wolisz `ownerId` zamiast `owner`, bo `owner` wskazuje raczej na obiekt literalny, a nie samo id.

2022-04-12 11:22 UTC, mkubera commented on routes/api/contacts.js
> +  const { _id: owner } = req.user;
tutaj pewnie wolisz `ownerId` zamiast `owner`, bo `owner` wskazuje raczej na obiekt literalny, a nie samo id.

2022-04-12 11:22 UTC, mkubera commented on routes/api/users.js
> +  await updateUserToken(user.id, token);
wysylka `200` nie zalezy od rezultatu update'u? 🤔

2022-04-12 11:22 UTC, mkubera commented on routes/api/users.js
> +        code: 201,
tu rowniez: brak conditional?

2022-04-12 12:21 UTC, PawelS1988 commented on routes/api/contacts.js
> +} = require("./utils");
niedopatrzenia, wpisałem właściwą nazwę

2022-04-12 12:21 UTC, PawelS1988 commented on routes/api/contacts.js
> +  const contact = await getContactById(req.params.contactId, owner);
poprawione dla czytelności

2022-04-12 12:25 UTC, PawelS1988 commented on routes/api/contacts.js
> +  const { _id: owner } = req.user;
poprawione

2022-04-12 12:33 UTC, PawelS1988 commented on routes/api/contacts.js
> +  const { _id: owner } = req.user;
poprawione

2022-04-12 16:18 UTC, PawelS1988 commented on routes/api/users.js
> +  await updateUserToken(user.id, token);
dodany conditional

2022-04-12 16:18 UTC, PawelS1988 commented on routes/api/users.js
> +        code: 201,
dodany conditional

2022-04-12 19:23 UTC, mkubera requested changes
Jeszcze kilka poprawek i jestes w domu 👍

2022-04-12 19:23 UTC, mkubera commented on routes/api/users.js
> +  }
A zadnego `else` nie wysylasz? ;) `40x` czy cus?

2022-04-12 19:23 UTC, mkubera commented on routes/api/users.js
> +    }
Tutaj tez na pewno bedziesz chcial jakas inna odpowiedz wyslac w razie niepowodzenia `password`.

2022-04-13 08:16 UTC, PawelS1988 commented on routes/api/users.js
> +    }
added

2022-04-13 08:16 UTC, PawelS1988 commented on routes/api/users.js
> +  }
added

2022-04-13 12:11 UTC, merged